{% set name = "donfig" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c586c607ff53792f9cd1dc5275ccc154cfd734b415c385c2a0436f17ce4e924

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python
    - pip
    - setuptools
    - pyyaml
  run:
    - python
    - pyyaml

test:
  imports:
    - donfig
    - donfig.tests
  requires:
    - pytest

about:
  home: https://github.com/pytroll/donfig
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python package for configuring a python package
  doc_url: https://donfig.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/donfig

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
    - mrocklin
    - jcrist
    - jhamman
