{% set name = "donfig" %}
{% set version = "0.8.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bef3413a4c1c601b585e8d297256d0c1470ea012afa6e8461dc28bfb7c23f52

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=62.6
    # versioneer ==0.28 is not available for py313
    - versioneer ==0.29
  run:
    - python
    - pyyaml

{% set deselect_tests = "" %}
# linux can`t collect permission with collect_yaml method.
{% set deselect_tests = " --deselect=donfig/tests/test_config.py::test_collect_yaml_permission_errors" %}  # [linux]

test:
  source_files:
    - donfig
  imports:
    - donfig
    - donfig.tests
  commands:
    - pip check
    - pytest -v {{ deselect_tests }} donfig/tests
  requires:
    - pip
    - pytest
    - cloudpickle
    - python

about:
  home: https://github.com/pytroll/donfig
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python package for configuring a python package
  doc_url: https://donfig.readthedocs.io/en/latest/
  dev_url: https://github.com/pytroll/donfig

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - pnuu
    - adybbroe
    - mrocklin
    - jcrist
    - jhamman
