travis:
  secure:
    BINSTAR_TOKEN: wL/cVRlyAWTX2mZoR58IoafXWFOE8bqbR6RCVQ+NzAw2PfuWpvGGD7eefwUZQZQ1NPu0gWttF7XF9C7NJEIH/tyrpdpJxtY/cywhIPwsV1JcuO1y2Z4zRUFkCwNuFisMifH2XFoA15Vb6K0Fq7p5JFqFYiqlWMg90RoVI4PGD5E4+2nvaBMAJFt5r7JoHMicgZXC5It1mgVCQWxM8rWeyg8JQUKR5BbZIevGn4XUKcttSnKta90t7L2ALyucEJDrumvrZxbq9lybMD8UTtx9jf1NAXhF0B7tE4GuiHg6VzcjbVgSSqVFmIiEyZIQceU1TU3wVKzghdXs41aUoe6zqa3L3bw2Z2QaFIGWQy2Nl4lTHPoUtdinfkxU4dNQKxj5nr81w5Q7ftCNRwVziM0iObRK9IbqgALDyGRBsD+HEHAGSkvq2O9wjNwpclTD+Cg0xfcQagcWNjRpS6SOxJXwedW6YnXM51zxPBU/kNsb+JpsbD/aelng6wdz2OnKMeJkvnhB2Z/FAI/jI6l4DiMwsUevGjClP064lco+Dsct/7LKIhXD+8ZcywYTgrSQcGIGP1tloi3fiugrVKqk/Xh2euPB0jmHK8FX60ibyCshQmVUlqrF54qimkjEE0QLf86mSRzBSB/Ay72Ddq+LseYNFzdhUsl5XXg6jP0iTsno6GY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
